### ISSUE TITLE
TODO camera ready

### ISSUE THREAD

**Issue by FissoreD** [FissoreD/HO-unif-for-free#9]
# REVIEW 1  

- [ ] Line 1368: The authors mention that one reason for delaying the
  application of substitutions is to keep the term structure indexable.
  One can imagine another reason for making such a delay, especially in
  a logic programming setting, is that failure can be encountered, and
  the work done in computing complete normal forms would be wasted.  Is
  there any evidence of that justification?
- [ ] It might interest the reader to explain what features of lambda Prolog
  that are not in Prolog remain in your specification.  For example,
  your code does not reduce HOU to first-order logic/Prolog.  The
  universal quantifier in goals and the pattern fragment unification are
  critical to your encoding, right?
- [x] line 26: This is the first time I've seen the "\beta\eta"
   conversion written as "\eta\beta$.  Is there a good reason to
   switch this order from the normal? (cf 8c08c2b742aa18e783922caa73cba9494c59f3fb)
- [x] line 70: "for the Coq's system" - rewrite (cf 7b86461cd0ccfab3fb54f161f077fab5b22b8b6c)
- [x] line 112: The reference for pattern unification is not [11] but
   Miller's 1991 paper in the J. of Logic and Computation. (cf 827b11dd2df213b9f446b77434fef8cb6591f00b)
- [x] line 247: Using "subscript" as a verb is odd.  Revise that
   sentence. (cf e040d56bb1ba83b1812178cd694e707daf654d71)
- [x] line 240: Definition 2.6 asks that a term is an eta expansion.
   Does this mean the term is an eta-redex, a term of the form 
   (lambda x. M x) where x is not free in M ? (cf 13113578ee7d77110bcd843f27e687171d04c026)
   > Comment : I do not really understand the remark. Maybe we should use $\lambda x.s_x$ in definition 2.6 to clarify 
      that $x$ is in the scope of $s$?
   > To avoid ambiguity we raname $\eta$-expansion into $\eta$-redex
- [x] line 1117 "desappears" (cf 8a88819c32712d3cbdfdc7f73259dd37f2b794ce)
- [x] line 1301: "heigenvariables" (cf dec5d599da6c69179ada79a9d9147fea81df92fd)
- [x] line 1311: "mathes" (cf d6de00e56cb20b9ecc31c1b26044c8a3bd73ea7c)
- [x] line 1324; "since it removes all THE data from THE rule's heads" (cf b84c753d8c07155198d7ff242045742c649df154)
- [x] line 1335: "to accommodate for the one" drop "for"? (cf 641a5577cdf02b3090f6a5bd1f15c77f8d4c13a4)
- [x] line 1355: "reather" (cf 1615f38561f68eefd857946969e847d302cb2217)
- [ ] An early attempt to reduce HOU (at least, 2nd order unification) to
   the pattern fragment can be found in Miller 1991 paper "Unification
   of Simply Typed Lambda-Terms as Logic Programming", ICLP91. That
   early approach does not provide the flexibility apparent in the
   present paper.

# REVIEW 2

- [x] The abstract is a little bit vague. It writes "more well-behaved" and 
      "problems" without any hint about what this might mean. A stronger 
      abstract would define the problem more clearly. (cf ed2941bdf3bb7061ad4f4468f016588181acb2ab)
- [x] "Instance forall_dec: ∀A P, Finite A → ∀x:A, Decision (P x) →Decision (∀x:A, P x)." 
      I think parentheses are missing around "∀x:A, Decision (P x)"? (cf d7dfb534cadf3976713c2a2d411be5aa5ee9924d)
- [x] "an Higher-Order Abstract Syntax" an => a (cf 42ef4a69fb38a94b09cdc1914f9e6ee4f3428b2e)
- [x] "for the Coq’s system" => "for Coq's type system" (cf 7b86461cd0ccfab3fb54f161f077fab5b22b8b6c)
- [ ] I'm a bit surprised it is called "good unification" and not "most general 
      unification"
- [x] "our real goal is to simulate the execution of an entire logic-program."
      I do not understand what you mean by a "real goal". Is this in contrast 
      to some goals that are not "real". I do not understand what this means. (cf b852fbe1bf783dbf20ebc5ef98fef548b1991841)
- [x] "so that the code of (𝑚𝑎𝑙𝑙𝑜𝑐) below can preserve" what can it preserve? (cf ba7af1098af7b7fe6fcb0ffa8c702fad5db8e867)
- [x] "ensures the mapping are bijective" are => is (cf 3e1f16535d4093bd59b346297cfe619091221147)
- [ ] In the definition of comp: "(arity z)" What is "arity z"?
  > Comment: in invariant 1, we give definition of arity 

# REVIEW 3

- [x] Usually, I think of the eta rule as a type-directed expansion (capturing
    a form of extensionality) rather than a contraction.  I wonder if the
    authors could expand on (a) on the significance of eta for the object
    language as it relates to type-class resolution, and (b) whether it might
    be possible to make encoding sufficiently aware of the object-language
    types as eta might be modeled via an expansion. (cf 13113578ee7d77110bcd843f27e687171d04c026)
   > Comment: to avoid ambiguity, we rename $\eta$-expansion into $\eta$-redex
- [x] In terms of related work, I might point out the paper
    "Higher-Order Logic Programming as Constraint Logic Programming" by
    Michaylov and Pfenning from PPCP 1993 which makes similar points as
    lines 1287-1291.  The Twelf manual also describes how nonpattern constraints
    are postponed, and how other constraint domains are integrated (Chapters 5.5 and 6),
    although not at the level of generality as CHR. (cf 3cafc5faf152f0ce1af2a22c4599f60aec40b3c9)
